'use client';
import {MAJORS,GROUPS,COURSE_TYPES,availableGroups,tableGrade,type Timetable,type CourseRule,type CourseAudience} from './curriculum';
export default function CourseClassificationEditor({course:c,table:t,onChange}:{course:Pick<CourseRule,'category'|'audiences'>;table:Timetable;onChange:(patch:Pick<CourseRule,'category'|'audiences'>)=>void}){
 function change(index:number,patch:Partial<CourseAudience>){onChange({audiences:c.audiences!.map((a,i)=>i===index?{...a,...patch}:a)})}
 return <div className="classification-editor"><label>条目类型<select value={c.category??'course'} onChange={e=>onChange({category:e.target.value as 'course'|'activity'})}><option value="course">课程</option><option value="activity">班级活动</option></select></label>
 <p className="editor-help">按培养方案填写适用范围；多行表示任一范围适用。不同专业或班型可分别标注必修 / 选修。无范围时保留为待核对，不会自动归为共同课程。</p>
 {(c.audiences??[]).map((a,i)=><div className="audience-row" key={i}><label>适用专业<select value={a.major} onChange={e=>change(i,{major:e.target.value as CourseAudience['major']})}><option value="all">{tableGrade(t)===1?'未分专业':'各专业共同'}</option>{tableGrade(t)!==1&&Object.entries(MAJORS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>课表范围<select value={a.group} onChange={e=>change(i,{group:e.target.value as CourseAudience['group']})}><option value="all">基础课表 / 各班型共同</option>{availableGroups(t).map(key=><option value={key} key={key}>{GROUPS[key]}</option>)}</select></label>{c.category!=='activity'&&<label>课程性质<select value={a.requirement} onChange={e=>change(i,{requirement:e.target.value as CourseAudience['requirement']})}>{(['unknown','required','elective'] as const).map(key=><option key={key} value={key}>{COURSE_TYPES[key]}</option>)}</select></label>}<button type="button" onClick={()=>onChange({audiences:c.audiences!.filter((_,j)=>j!==i)})}>移除范围</button></div>)}
 <button type="button" onClick={()=>onChange({audiences:[...(c.audiences??[]),{major:'all',group:'all',requirement:'unknown'}]})}>添加适用范围</button></div>
}
