'use client';
import {useEffect,useRef,useState} from 'react';
import {CURRICULUM_KEY,parseWeeks,validateCurriculum,type Curriculum,type Timetable} from './curriculum';
import CourseClassificationEditor from './course-classification-editor';
type Draft=Omit<Timetable,'courses'> & {courses:(Omit<Timetable['courses'][number],'weeks'> & {weeks:string})[]};
const draftOf=(data:Curriculum):Draft[]=>data.timetables.map(t=>({...t,courses:t.courses.map(c=>({...c,weeks:c.weeks.join(',')}))}));
export default function TimetableEditor({value,onSave,onClose}:{value:Curriculum;onSave:(data:Curriculum)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState(()=>draftOf(value));const [index,setIndex]=useState(0);const [error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);const file=useRef<HTMLInputElement>(null);const t=draft[index];
 useEffect(()=>{dialog.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[]);
 const update=(patch:Partial<Draft>)=>setDraft(old=>old.map((x,i)=>i===index?{...x,...patch}:x));
 function data(){return validateCurriculum({version:1,timetables:draft.map(t=>({...t,courses:t.courses.map(c=>({...c,weeks:parseWeeks(c.weeks)}))}))})}
 function save(){try{const next=data();const previous=localStorage.getItem(CURRICULUM_KEY);if(previous)localStorage.setItem(CURRICULUM_KEY+'-previous',previous);localStorage.setItem(CURRICULUM_KEY,JSON.stringify(next));onSave(next);onClose()}catch(e){setError(e instanceof Error?e.message:'保存失败')}}
 function download(){try{const blob=new Blob([JSON.stringify(data(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='年级课表.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e instanceof Error?e.message:'导出失败')}}
 async function importFile(f:File|undefined){if(!f)return;try{if(f.size>1000000)throw new Error('课表文件不能超过 1 MB');const next=validateCurriculum(JSON.parse(await f.text()));setDraft(draftOf(next));setIndex(0);setError('')}catch(e){setError(e instanceof Error?e.message:'无法读取课表')}}
 return <dialog ref={dialog} className="timetable-editor" onCancel={e=>{e.preventDefault();onClose()}} aria-labelledby="editor-title"><h2 id="editor-title">更新年级课表</h2><p className="dialog-intro">修改或导入后，点击“保存课表”生效。仅保存在本机浏览器；可导出备份，供下学期更新或发布使用。</p><div className="editor-tools"><button type="button" onClick={()=>file.current?.click()}>导入 JSON</button><button type="button" onClick={download}>导出 JSON</button><button type="button" onClick={()=>{setDraft([...draft,{id:crypto.randomUUID(),label:'新年级',term:'新学期',week1Monday:'',courses:[],overrides:[]}]);setIndex(draft.length)}}>添加年级</button><input hidden type="file" ref={file} accept=".json,application/json" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value=''}}/></div><p className="editor-help">导入会替换下面的待保存课表；点击“放弃修改”可保留原课表。</p>
 <label className="field-label">编辑年级<select value={index} onChange={e=>setIndex(Number(e.target.value))}>{draft.map((t,i)=><option key={t.id} value={i}>{t.label} · {t.term}</option>)}</select></label>
 {t&&<><div className="editor-fields"><label>年级名称<input value={t.label} onChange={e=>update({label:e.target.value})}/></label><label>年级阶段<select value={t.grade??({大一:1,大二:2,大三:3,大四:4}[t.label]||0)} onChange={e=>update({grade:Number(e.target.value)||undefined})}><option value={0}>未指定</option>{[1,2,3,4].map(g=><option key={g} value={g}>大{'一二三四'[g-1]}</option>)}</select></label><label>学期<input value={t.term} onChange={e=>update({term:e.target.value})}/></label><label>第 1 周星期一<input type="date" value={t.week1Monday} onChange={e=>update({week1Monday:e.target.value})}/></label></div>
 <div className="editor-courses">{t.courses.map((c,i)=><details key={c.id}><summary>{c.name||'新课程'} · 周{'一二三四五六日'[c.weekday-1]} {c.start}–{c.end}</summary><div className="editor-fields">{(['name','location','weeks'] as const).map(key=><label key={key}>{key==='name'?'课程名称':key==='location'?'地点':'周次，如 1-8,10-17'}<input value={c[key]} onChange={e=>update({courses:t.courses.map((x,j)=>j===i?{...x,[key]:e.target.value}:x)})}/></label>)}<label>星期<select value={c.weekday} onChange={e=>update({courses:t.courses.map((x,j)=>j===i?{...x,weekday:Number(e.target.value)}:x)})}>{[1,2,3,4,5,6,7].map(d=><option key={d} value={d}>周{'一二三四五六日'[d-1]}</option>)}</select></label>{(['start','end'] as const).map(key=><label key={key}>{key==='start'?'开始':'结束'}时间<input type="time" value={c[key]} onChange={e=>update({courses:t.courses.map((x,j)=>j===i?{...x,[key]:e.target.value}:x)})}/></label>)}</div><CourseClassificationEditor course={c} table={{...t,courses:[]}} onChange={patch=>update({courses:t.courses.map((x,j)=>j===i?{...x,...patch}:x)})}/><button className="editor-remove" onClick={()=>update({courses:t.courses.filter((_,j)=>j!==i)})}>移除此课程（保存后生效）</button></details>)}</div>
 <button className="editor-add" onClick={()=>update({courses:[...t.courses,{id:crypto.randomUUID(),name:'新课程',location:'',weekday:1,weeks:'1-17',start:'08:00',end:'09:40'}]})}>添加课程</button>
 <details className="editor-overrides"><summary>节假日、调休日期</summary><p className="editor-help">指定日期停课，或改上另一日期的课程；按被替代日期的周次计算。</p>{t.overrides.map((o,i)=><div className="override-row" key={i}><label>调整日期<input type="date" value={o.date} onChange={e=>update({overrides:t.overrides.map((x,j)=>j===i?{...x,date:e.target.value}:x)})}/></label><label>改上哪天的课（留空为停课）<input type="date" value={o.sourceDate||''} onChange={e=>update({overrides:t.overrides.map((x,j)=>j===i?{...x,sourceDate:e.target.value||null}:x)})}/></label><button onClick={()=>update({overrides:t.overrides.filter((_,j)=>j!==i)})}>移除</button></div>)}<button className="editor-add" onClick={()=>update({overrides:[...t.overrides,{date:'',sourceDate:null}]})}>添加日期调整</button></details></>}
 {error&&<p role="alert" className="feedback error">{error}</p>}<div className="dialog-actions"><button onClick={onClose}>放弃修改</button><button className="primary" onClick={save}>保存课表</button></div></dialog>
}
